import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

const API_URL = "https://canvas.shanecranor.workers.dev/?req="
async function fetchData() {
  const response = await fetch(
    `${API_URL}api/v1/courses?enrollment_state=active`
  );
  return (await response.json());
}
function parseData(data) {
  return data.map(
    (course) => {
      return <p>{course.name}</p>
    }
  )
}
const Home: NextPage = () => {
  const [data, setData] = useState();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={async () => setData(await fetchData())}>get data</button><br />
        {data ? parseData(data) : "not loaded"}

      </main>
    </>
  )
}

export default Home
