export const IGNORE_CLASSES = [
  'Canvas API project course',
  'CASA Advising',
  'Sandbox - ',
  'SANS Security Awareness Course',
  'Tutoring',
  'Operation Oredigger',
  'Makerspace Training Portal',
  'Computer Science Student Portal',
  'Undergraduate Commencement',
  'Graduate Commencement',
  'Portal',
  'Physical Metallurgy Laboratory',
  'SAIL',
  'BSO',
  'Reservations',
  'Check-Out',
];
